name: "Publish HA Fusion"

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  publish:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Verify DockerHub Login
        run: |
          echo "Testing DockerHub login context..."
          docker info

      - name: Publish Docker Images
        uses: home-assistant/builder@master
        with:
          args: |
            --all \
            --target /data \
            --docker-hub sefetzer \
